CREATE TABLE IF NOT EXISTS `users` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `name` TINYTEXT,
  `email` TEXT,
  `password` TINYTEXT,
  `creation_date` TIMESTAMP,
  `description` TEXT,
  `is_admin` BOOLEAN,
  `ban_date` DATETIME,
  `image_link` TEXT
);

CREATE TABLE IF NOT EXISTS `dvds` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `title` TINYTEXT,
  `description` TEXT,
  `director` TINYTEXT,
  `genre` TINYTEXT,
  `year_of_production` SMALLINT,
  `addition_date` TIMESTAMP,
  `available_amount` TINYINT,
  `image_link` TEXT
);

CREATE TABLE IF NOT EXISTS `rents` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `id_user` INT,
  `id_dvd` INT,
  `rent_date` DATETIME,
  `return_deadline` DATETIME,
  `return_date` DATETIME
);

-- users - records
INSERT INTO `users` VALUES (NULL, "tester1", "gigatester69xd@gmail.com", "018712ad55e557ab5f9bfe76688e1cae2e15aaece5f9358510ddd461ab5dcad8", NULL, "Lubię truskawki.", 0,  0, "http://omnident.com.tw/img/400x400/p6.jpg");
INSERT INTO `users` VALUES (NULL, "admin1", "swietyyoda@gmail.com", "f7a2c1a9b8b9ab69dcd135fc6f54dfa46c5bf04f54383b3a04163293fe20faea", NULL, "Lubię gile z nosa.", 1,  0, "https://www.ibm.com/blogs/southeast-europe/wp-content/uploads/2019/02/securitythumbnail400x400.png");
INSERT INTO `users` VALUES (NULL, "Jakub Szyndler", "asheytm@gmail.com", "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9", NULL, "Mam wielkiego dicka.", 1,  0, "https://upload.wikimedia.org/wikipedia/commons/3/35/Eye_reasonably_small_400x400.jpg");
INSERT INTO `users` VALUES (NULL, "Piotr Stocki", "stockipiotrek1@gmail.com", "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9", NULL, "Mam średniego dicka.", 1,  0, "http://omnident.com.tw/img/400x400/05.jpg");
INSERT INTO `users` VALUES (NULL, "Bartosz Pydych", "pydychbartosz10@gmail.com", "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9", NULL, "Mam mini dicka.", 1,  0, "https://upload.wikimedia.org/wikipedia/commons/9/94/Image_400x400.png");
INSERT INTO `users` VALUES (NULL, "Michał Płuska", "michal24pluska@gmail.com", "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9", NULL, "Mam włochatego dicka.", 1,  0, "http://omnident.com.tw/img/400x400/do2.png");

-- dvds - records
INSERT INTO `dvds` VALUES (NULL, "Avatar: Istota wody", "Akcja filmu Avatar: Istota wody rozgrywa się ponad dziesięć lat po wydarzeniach z pierwszej części. To opowieść o rodzinie Jake’a i Neytiri oraz ich staraniach, by zapewnić bezpieczeństwo sobie i swoim dzieciom, mimo tragedii, których wspólnie doświadczają i bitew, które muszą stoczyć, aby przeżyć.", "James Cameron", "Science Fiction", 2022, NULL, 5, "https://i1.fdbimg.pl/x1/zj5yrl42/400x580_rkss4v.jpg");
INSERT INTO `dvds` VALUES (NULL, "After 2", "Aby zapomnieć o Hardinie, Tessa rzuca się w wir pracy. Chłopak nie zamierza się jednak poddać.", "Roger Kumble", "Romantyczny", 2020, NULL, 3, "https://i1.fdbimg.pl/x1/mhiaxe12/400x580_qfgazh.jpg");
INSERT INTO `dvds` VALUES (NULL, "After. Ocal mnie", "Po tym jak Tessa podejmuje najważniejszą decyzję swojego życia, wszystko się zmienia. Hardin podaje w wątpliwość wszystko, o co tak walczyli.", "Castille Landon", "Romantyczny", 2021, NULL, 7, "https://i1.fdbimg.pl/x1/l9paiv22/400x580_qydsbz.jpg");
INSERT INTO `dvds` VALUES (NULL, "After", "Tessa rozpoczyna wymarzone studia. Jej uporządkowany świat staje na głowie, kiedy poznaje buntowniczego Hardina.", "Jenny Gage", "Romantyczny", 2019, NULL, 4, "https://i1.fdbimg.pl/x1/6w3rabz1/400x580_qen1xy.jpg");
INSERT INTO `dvds` VALUES (NULL, "Minionki: Wejście Gru", "Minionki Kevin, Stuart, Bob oraz Otto muszą ratować młodego Gru, który popadł w konflikt z grupą super złoczyńców znaną jako Vicious 6.", "Kyle Balda", "Bajka", 2022, NULL, 7, "https://i1.fdbimg.pl/x1/5nbfvm02/400x580_r4gh6x.jpg");
INSERT INTO `dvds` VALUES (NULL, "After 4. Bez siebie nie przetrwamy", "Związek Tessy i Hardina przeszedł tyle prób, że wydaje się trwalszy i silniejszy niż kiedykolwiek. Jednak, gdy na jaw wychodzą rodzinne tajemnice obojga kochanków.", "Castille Landon", "Romantyczny", 2022, NULL, 3, "https://i1.fdbimg.pl/x1/sy3cw642/400x580_rfla6r.jpg");
INSERT INTO `dvds` VALUES (NULL, "Avengers: Koniec gry", "Po wymazaniu połowy życia we Wszechświecie przez Thanosa Avengersi starają się zrobić wszystko, co konieczne, aby pokonać szalonego tytana.", "Anthony Russo", "Akcji", 2019, NULL, 5, "https://i1.fdbimg.pl/x1/62vcwcz1/400x580_posxfl.jpg");
INSERT INTO `dvds` VALUES (NULL, "Underdog", "Borys Kosa Kosiński to zawodnik MMA, który jest u szczytu formy. W najważniejszej walce ze swoim największym rywalem Deni Takaevem popełnia błąd, który przekreśla jego karierę.", "Maciej Kawulski", "Akcji", 2019, NULL, 6, "https://i1.fdbimg.pl/x1/wvm8cwy1/400x580_r75uny.jpg");
INSERT INTO `dvds` VALUES (NULL, "Epoka lodowcowa: Przygody dzikiego Bucka", "Bracia oposy postanawiają znaleźć własne miejsce, ale zostają uwięzieni w podziemnej jaskini. Zostają uratowani przez łasicę Buck Wild i razem wyruszają na misję ratowania Zaginionego Świata przed dominacją dinozaurów.", "John C. Donkin", "Bajka", 2022, NULL, 3, "https://i1.fdbimg.pl/x1/p01pna32/400x580_r3u4ou.jpg");
INSERT INTO `dvds` VALUES (NULL, "Był sobie pies 2", "Bailey dostaje od swojego ukochanego Ethana nowy cel: ma opiekować się jego wnuczką – CJ. Z biegiem czasu dziewczynka dorasta i wyzwania dla psa stają się coraz większe.", "Gail Mancuso", "Dramat", 2019, NULL, 7, "https://i1.fdbimg.pl/x1/gj69ygz1/400x580_pq9g9l.jpg");
INSERT INTO `dvds` VALUES (NULL, "Thor: Miłość i grom", "Thor: Miłość i grom ukazuje Boga Piorunów wraz z Królewską Valkirią, Korgiem i swoją byłą, Jane Foster, która posługuje się Mjolnirem, w starciu z galaktycznym mordercą znanym jako Gorr Rzeźnik Bogów.", "Taika Waititi", "Akcji", 2022, NULL, 3, "https://i1.fdbimg.pl/x1/y1kkw142/400x580_rdn8u9.jpg");
INSERT INTO `dvds` VALUES (NULL, "Szybcy i wściekli 9", "Cypher prosi Jakoba o pomoc w zemście na Domie i jego drużynie.", "Justin Lin", "Film akcji", 2021, NULL, 5, "https://i1.fdbimg.pl/x1/vr1owl02/400x580_q508nq.jpg");
INSERT INTO `dvds` VALUES (NULL, "Kot w butach: Ostatnie życzenie", "Kot w Butach odkryje, że jest pasjonatem przygód. Wykorzystał już wszystkie swoje osiem z dziewięciu istnień. Postanawia wyruszyć w podróż, aby znaleźć mityczne Ostatnie Życzenie i przywrócić swoje dziewięć żyć.", "Joel Crawford", "Bajka", 2022, NULL, 4, "https://i1.fdbimg.pl/x1/wwsbgo32/400x580_r8sx1s.jpg");
INSERT INTO `dvds` VALUES (NULL, "25 lat niewinności. Sprawa Tomka Komendy", "Historia młodego mężczyzny, który został niesłusznie skazany na dwadzieścia pięć lat pozbawienia wolności za rzekomy gwałt i morderstwo nastolatki.", "25 lat niewinności. Sprawa Tomka Komendy 2020 reżyser", "Dramat", 2020, NULL, 4, "https://i1.fdbimg.pl/x1/k2uz9g12/400x580_qfxu6k.jpg");
INSERT INTO `dvds` VALUES (NULL, "Psy 3. W imię zasad", "Po 25 latach odsiadki Franz Maurer wkracza w nową Polskę, gdzie nic nie jest takie, jak zapamiętał. Wkrótce ponownie spotyka Nowego.", "Władysław Pasikowski", "Film akcji", 2020, NULL, 7, "https://i1.fdbimg.pl/x1/73rvyg02/400x580_q388jv.jpg");
INSERT INTO `dvds` VALUES (NULL, "Krzyk 6", "Po ostatnich zabójstwach zamaskowanego mordercy czwórka ocalałych zostawia za sobą Woodsboro i rozpoczyna nowy rozdział w życiu. Sprawy nie toczą się jednak po ich myśli, ponieważ Ghostface powraca i jest żądny ofiar.", "Tyler Gillett", "Horror", 2023, NULL, 5, "https://i1.fdbimg.pl/x1/ei3aor42/400x580_rmx7ye.jpg");
INSERT INTO `dvds` VALUES (NULL, "Terminator: Mroczne przeznaczenie", "Sarah Connor powraca, aby chronić dziewczynę imieniem Dani przed nowym Terminatorem Rev-9.", "Tim Miller", "Science Fiction", 2019, NULL, 4, "https://i1.fdbimg.pl/x1/yluv1802/400x580_q00ofd.jpg");
INSERT INTO `dvds` VALUES (NULL, "Annabelle wraca do domu", "Ed i Lorraine Warren aby uniemożliwić Annabelle dokonywanie kolejnych okrutnych czynów zamykają ją w odosobnionym pokoju.", "Gary Dauberman", "Horror", 2019, NULL, 4, "https://i1.fdbimg.pl/x1/gid3rkz1/400x580_prmpp2.jpg");
INSERT INTO `dvds` VALUES (NULL, "W lesie dziś nie zaśnie nikt", "Grupa nastolatków uzależnionych od technologii trafia na… obóz offline. Wspólna wędrówka po lasach bez dostępu do smartfonów nie zakończy się jednak tak, jak zaplanowali to organizatorzy.", "Bartosz M. Kowalski", "Horror", 2020, NULL, 7, "https://i1.fdbimg.pl/x1/f9bxij02/400x580_q45dfm.jpg");
INSERT INTO `dvds` VALUES (NULL, "Teściowie", "Czy wesele po odwołanym ślubie to przepis na katastrofę? Owszem. I to jaką! Dwie rodziny różni wszystko – pochodzenie, status, zawartość portfela, gust. Rodzice pana młodego (Maja Ostaszewska i Marcin Dorociński) i panny młodej (Izabela Kuna i Adam Woronowicz) początkowo są w szoku. Co takiego się stało? Kto zawinił?", "Jakub Michalczuk", "Komedia", 2021, NULL, 7, "https://i1.fdbimg.pl/x1/8frjxn22/400x580_qw3kgk.jpg");
INSERT INTO `dvds` VALUES (NULL, "Boże Ciało", "Dwudziestoletni Daniel zostaje warunkowo zwolniony z poprawczaka. Wyjeżdża na drugi koniec Polski, żeby pracować w stolarni, ale zamiast tego zaczyna udawać księdza.", "Jan Komasa", "Dramat", 2019, NULL, 7, "https://i1.fdbimg.pl/x1/sk7gt102/400x580_r66bva.jpg");
INSERT INTO `dvds` VALUES (NULL, "Le Mans ’66", "Na zlecenie Henryego Forda II amerykański projektant Carroll Shelby i brytyjski kierowca Ken Miles podejmują wyzwanie pokonania samochodów ekipy Ferrari w 24-godzinnym wyścigu Le Mans.", "James Mangold", "Film akcji", 2019, NULL, 6, "https://i1.fdbimg.pl/x1/t1fzwb02/400x580_q1er5g.jpg");
INSERT INTO `dvds` VALUES (NULL, "Mistrz", "Rok 1940. Pięściarz Tadeusz Pietrzykowski trafia do niemieckiego obozu koncentracyjnego. Aby przeżyć bierze udział w walkach na ringu.", "Maciej Barczewski", "Dramat", 2020, NULL, 6, "https://i1.fdbimg.pl/x1/w85hvq22/400x580_qwtxos.jpg");
INSERT INTO `dvds` VALUES (NULL, "Proceder", "Tomasz Chada (Piotr Witkowski) nawija rapowe kawałki, pali trawę, a w wolnych chwilach kradnie bryki dla warszawskiej mafii. Złodziejski proceder traktuje jako etap przejściowy – chce tworzyć muzykę. Łudzi się, że dzięki szybko zarobionej kasie będzie mógł wynająć studio, nagrać płytę i zerwać z przeszłością.", "Michal Wegrzyn", "Dramat", 2019, NULL, 7, "https://i1.fdbimg.pl/x1/5rtwfb32/400x580_r44adl.jpg");
INSERT INTO `dvds` VALUES (NULL, "Ślicznotki", "Inspirowana prawdziwym wydarzeniem, o którym głośno było w 2015 roku dzięki artykułowi w New York Magazine, historia byłych tancerek nocnego klubu, które mszczą się na swoich klientach (bankierach z Wall Street), za ich ordynarne zachowanie.", "Lorene Scafaria", "Komedia", 2019, NULL, 7, "https://i1.fdbimg.pl/x1/6jlmwyz1/400x580_pwq598.jpg");
INSERT INTO `dvds` VALUES (NULL, "Więźniowie dzielnicy", "Kiedy lokalny gang narkotykowy rekrutuje do swoich szeregów dziesięcioletniego chłopca, jego starszy brat Lucas znajduje pomoc u pogrążonego w depresji weterana z zespołem stresu pourazowego.", "Lior Geller", "Film akcji", 2019, NULL, 4, "https://i1.fdbimg.pl/x1/kaf47zy1/400x580_pjvd43.jpg");
INSERT INTO `dvds` VALUES (NULL, "Jumanji: Następny poziom", "Gra Jumanji nie pozwala o sobie zapomnieć. Nawet wówczas, gdy, mogłoby się wydawać, jest już całkiem zniszczona. Jeden z byłych graczy podejmuje decyzję, by wkroczyć w jej świat z własnej woli.", "Jake Kasdan", "Film akcji", 2019, NULL, 5, "https://i1.fdbimg.pl/x1/8kju4602/400x580_pzbtpt.jpg");
INSERT INTO `dvds` VALUES (NULL, "Halloween. Finał", "Laurie Strode po raz ostatni staje do walki z wcieleniem zła, Michaelem Myersem. Tylko jedno z nich przeżyje.", "David Gordon Green", "Horror", 2022, NULL, 3, "https://i1.fdbimg.pl/x1/fss14f42/400x580_rief1q.jpg");
INSERT INTO `dvds` VALUES (NULL, "Nie czas umierać", "James Bond (Daniel Craig) opuszcza czynną służbę i cieszy się spokojnym życiem na Jamajce. Tymczasem jednak jego stary przyjaciel Felix Leiter (Jeffrey Wright) z CIA zwraca się do niego o pomoc. Misja uratowania porwanego naukowca okazuje się o wiele bardziej zdradliwa, niż mogłoby się wydawać.", "Cary Joji Fukunaga", "Film akcji", 2021, NULL, 7, "https://i1.fdbimg.pl/x1/p1ymjg12/400x580_qz91bg.jpg");
INSERT INTO `dvds` VALUES (NULL, "Żużel", "Mistrz motocyklowy Lowa (Tomasz Ziętek) jest obiektem westchnień kobiet i źródłem zazdrości rywali z toru (Mateusz Kościukiewicz). Pogodny, miły dla ludzi, „zwyczajny”, ma frajdę z życia i tego, co robi. Jednak szelmowski uśmiech chłopaka skrywa codzienne zmagania ze strachem, widmem kontuzji i wypadków na żużlowych.", "Dorota Kędzierzawska", "Dramat", 2020, NULL, 3, "https://i1.fdbimg.pl/x1/thl9gp22/400x580_qw7anl.jpg");
INSERT INTO `dvds` VALUES (NULL, "MEGAN", "Gemma projektuje realistyczną lalkę, która zwie się M3GAN i programuje jej sztuczną inteligencję. Kiedy siostrzenica Cady zostaje nagle osierocona, robotyczna zabawka ma się z nią zaprzyjaźnić. Początkowo wszystko idzie zgodnie z planem, ale z czasem opiekuńcza natura maszyny ujawnia swoją złośliwą stronę, której nikt się nie spodziewał.", "James Wan", "Horror", 2023, NULL, 4, "https://i1.fdbimg.pl/x1/c6ijyt42/400x580_rnqu28.jpg");
INSERT INTO `dvds` VALUES (NULL, "Pętla", "Patryk Vega powraca do Służb Specjalnych i Pitbulla z najnowszym filmem Pętla. Pokazuje prawdziwą historię siatki klubów nocnych kontrolowanych przez agenta CBŚP, która stała się elementem gry ukraińskich i rosyjskich służb specjalnych poprzez sekstaśmy z udziałem polityków, celebrytów i duchownych.", "Patryk Vega", "Dramat", 2020, NULL, 7, "https://i1.fdbimg.pl/x1/knd13k32/400x580_r78akr.jpg");
INSERT INTO `dvds` VALUES (NULL, "Lokal zamknięty", "Próba oskubania skorumpowanego polityka, kończy się dla rabusiów kwarantanną w pokojach agencji towarzyskiej.", "Krzysztof Jankowski", "Komedia", 2021, NULL, 7, "https://i1.fdbimg.pl/x1/05t9xi22/400x580_qtup4q.jpg");
INSERT INTO `dvds` VALUES (NULL, "Listy do M. 5", "Melowi jak zwykle nic nie wychodzi. Zbieg okoliczności sprawia, że staje się bohaterem mimo woli, a jego nie zawsze kryształowy charakter znowu zostaje wystawiony na próbę. Wojciech, który nie czuje wszechobecnej radosnej atmosfery, spotyka na swojej drodze kogoś, kto zmienia jego świąteczne plany.", "Łukasz Jaworski", "Romantyczny", 2022, NULL, 7, "https://i1.fdbimg.pl/x1/trbkyf42/400x580_ripein.jpg");
INSERT INTO `dvds` VALUES (NULL, "Asterix i Obeliks: Imperium Smoka", "Jest rok 50 p.n.e. Cesarzowa Chin, w wyniku zamachu stanu przeprowadzonego przez zdradzieckiego księcia, zostaje uwięziona. Córka porwanej władczyni – księżniczka Sass-Yi, wraz ze swoim wiernym ochroniarzem i fenickim kupcem wyrusza do odległej Galii, aby szukać pomocy dla swojego kraju.", "Guillaume Canet", "Film akcji", 2023, NULL, 5, "https://i1.fdbimg.pl/x1/aop6qv42/400x580_rodqwa.jpg");
INSERT INTO `dvds` VALUES (NULL, "Szybcy i wściekli: Hobbs i Shaw", "Stróż prawa Luke Hobbs i wyrzutek Deckard Shaw łączą swoje siły przeciwko cybernetycznie zmodyfikowanemu przestępcy zagrażającemu całej ludzkości.", "David Leitch", "Film akcji", 2019, NULL, 4, "https://i1.fdbimg.pl/x1/g2bk6qz1/400x580_ptl2zr.jpg");
INSERT INTO `dvds` VALUES (NULL, "Król Lew", "W wyniku podstępu Skazy prawowity władca afrykańskiej sawanny, Simba, zostaje wygnany. Razem z dwójką przyjaciół zamierza odzyskać tron.", "Jon Favreau", "Bajka", 2019, NULL, 7, "https://i1.fdbimg.pl/x1/3aq7frz1/400x580_pu15nw.jpg");
INSERT INTO `dvds` VALUES (NULL, "Terrifier 2. Masakra w Święta", "Po wskrzeszeniu przez złowrogą istotę, Klaun powraca do bojaźliwego miasteczka Miles County, gdzie w noc Halloween obiera za cel nastolatkę i jej młodszego brata.", "Damien Leone", "Horror", 2022, NULL, 6, "https://i1.fdbimg.pl/x1/bnjjnc42/400x580_rhijzv.jpg");
INSERT INTO `dvds` VALUES (NULL, "Dziewczyny z Dubaju", "Emi to młoda ambitna dziewczyna, która od lat marzy o wielkim świecie. Gdy tylko nadarza się okazja, bez wahania wskakuje w jego tryby, stając się ekskluzywną damą do towarzystwa.", "Maria Sadowska", "Erotyczny", 2021, NULL, 6, "https://i1.fdbimg.pl/x1/1dsrk232/400x580_r0xebn.jpg");
INSERT INTO `dvds` VALUES (NULL, "Na pełny etat", "Julie (Laure Calamy) walczy sama o wychowanie dwójki dzieci na wsi i utrzymanie pracy w paryskim pałacu. Kiedy w końcu dostaje awans na stanowisko sprawy zaczynają się komplikować.", "Eric Gravel", "Dramat", 2021, NULL, 3, "https://i1.fdbimg.pl/x1/behzv542/400x580_rf2vhs.jpg");
INSERT INTO `dvds` VALUES (NULL, "Dziwny świat", "Bohaterowie rozpoczynają podróż do miejsca, w którym nic nie jest takie, jakie mogłoby się początkowo wydawać.", "Don Hall", "Bajka", 2022, NULL, 5, "https://i1.fdbimg.pl/x1/44nail42/400x580_rkpb14.jpg");
INSERT INTO `dvds` VALUES (NULL, "Jak zostać gwiazdą", "Music Race to popularny talent-show, który szuka muzycznych talentów z całej Polski. Wkrótce do programu zgłasza się Ostra. Dzięki niej program zyskuje oglądalność.", "Anna Wieczur-Bluszcz", "Komedia", 2020, NULL, 5, "https://i1.fdbimg.pl/x1/by4r3k12/400x580_qhbfj3.jpg");
INSERT INTO `dvds` VALUES (NULL, "Życie seksualne studentek", "Historia czterech współlokatorek z college’u, które rozpoczynają studia na prestiżowym Essex College. Oto prawdziwa fuzja sprzeczności i hormonów.", "Lila Neugebauer", "Erotyczny", 2021, NULL, 3, "https://i1.fdbimg.pl/x1/yzxbgo32/400x580_r8sx3m.jpg");
INSERT INTO `dvds` VALUES (NULL, "Na bank się uda", "Trzech starszych panów dokonuje napadu na bank. Po przyjeździe policji okazuje się, że nic nie zginęło.", "Szymon Jakubowski", "Komedia", 2019, NULL, 6, "https://i1.fdbimg.pl/x1/fypfrpz1/400x580_r7gpd2.jpg");
INSERT INTO `dvds` VALUES (NULL, "Gwiezdne wojny: Skywalker. Odrodzenie", "Członkowie organizacji Ruchu Oporu ponownie stawiają czoła Najwyższemu Porządkowi.", "J.J. Abrams", "Film akcji", 2019, NULL, 6, "https://i1.fdbimg.pl/x1/7si5i702/400x580_pztkpj.jpg");
INSERT INTO `dvds` VALUES (NULL, "Godzilla vs. Kong", "Tytany chodzą wolne po Ziemi, a firma Monarch stara się odkryć tajemnicę ich powstania. Pojawia się również grupa ludzi, która zamierza unicestwić je wszystkie, a pośrodku tych wydarzeń stoją King Kong i Godzilla – gotowi do starcia o miano prawdziwego Króla Potworów.", "Adam Wingard", "Science Fiction", 2021, NULL, 3, "https://i1.fdbimg.pl/x1/84bvx022/400x580_qndmsi.jpg");
INSERT INTO `dvds` VALUES (NULL, "Obecność 3: Na rozkaz diabła", "Rok 1981. Małżeństwo Warren bada sprawę mężczyzny oskarżonego o morderstwo. Sprawca jednak utrzymuje, że za zbrodnie odpowiedzialny jest potężny demon, władający jego ciałem.", "Michael Chaves", "Horror", 2021, NULL, 6, "https://i1.fdbimg.pl/x1/uvlo7g22/400x580_qw7al7.jpg");
INSERT INTO `dvds` VALUES (NULL, "Adepci policyjni", "Opowieść o wyzwaniach, motywacji i pasji dwójki studentów pierwszego roku Koreańskiego Narodowego Uniwersytetu Policyjnego.", "Lee Ha-na", "Film akcji", 2022, NULL, 7, "https://i1.fdbimg.pl/x1/9bf81j42/400x580_rjt8sk.jpg");
INSERT INTO `dvds` VALUES (NULL, "Uncharted", "Filmowa adaptacja jednej z najpopularniejszych gier ostatnich lat. Widowiskowa opowieść o przygodach nieustraszonego poszukiwacza skarbów Nathana Drake’a. Tylko jego sprawność, tylko jego intelekt, spryt i determinacja mogą doprowadzić do odnalezienia mitycznej krainy złota – El Dorado.", "Ruben Fleischer", "Film akcji", 2022, NULL, 3, "https://i1.fdbimg.pl/x1/tz7qwf32/400x580_r5q6k6.jpg");
INSERT INTO `dvds` VALUES (NULL, "Prorok", "Prymas jest przywódcą duchowym i wizjonerem, który pertraktuje z władzami komunistycznymi, by wynegocjować więcej praw dla Kościoła i uciemiężonego narodu. Pozorne porozumienie zmienia się w cichą wojnę, walkę o wolność religijną i godność człowieka.", "Michal Kondrat", "Dokumnet", 2022, NULL, 4, "https://i1.fdbimg.pl/x1/fgg35j42/400x580_rjumue.jpg");
INSERT INTO `dvds` VALUES (NULL, "Tylko nie mów nikomu", "Dziennikarz śledczy rozmawia z dziewięcioma księżmi katolickimi, którzy dopuścili się zbrodni pedofilii i molestowania nieletnich, a także ich ofiarami.", "Tomasz Sekielski", "Dokumnet", 2019, NULL, 4, "https://i1.fdbimg.pl/x1/kam93kz1/400x580_pre4wj.jpg");
INSERT INTO `dvds` VALUES (NULL, "Lupin", "Kiedy Assane Diop był nastolatkiem, jego życiem wstrząsnęła śmierć ojca, oskarżonego o przestępstwo, którego nie popełnił. 25 lat później Assane pomści go, inspirując się opowiadaniami „Arsène Lupin, dżentelmen włamywacz”.", "Marcela Said", "Film akcji", 2021, NULL, 7, "https://i1.fdbimg.pl/x1/t2zy3722/400x580_qpll8d.jpg");
INSERT INTO `dvds` VALUES (NULL, "Następcy 3", "Nastoletnie dzieci największych złoczyńców Disneya wracają na Wyspę Potępionych aby rekrutować nową grupę złowieszczych potomków do szkoły Auradon.", "Kenny Ortega", "Musical", 2019, NULL, 3, "https://i1.fdbimg.pl/x1/7u91kfz1/400x580_qh3t92.jpg");
INSERT INTO `dvds` VALUES (NULL, "Ptaki nocy", "Po rozstaniu z Jokerem Harley Quinn staje się zwierzyną łowną. Wkrótce dołącza jednak do drużyny superbohaterek, aby stoczyć walkę z królem zbrodni.", "Cathy Yan", "Film akcji", 2020, NULL, 3, "https://i1.fdbimg.pl/x1/w21b0k02/400x580_q4bmow.jpg");
INSERT INTO `dvds` VALUES (NULL, "Black Adam", "Prawie 5000 lat po otrzymaniu olbrzymich mocy starożytnych bogów - i prawie równoczesnym uwięzieniu - Black Adam (Dwayne Johnson) zostaje uwolniony z ziemskiego grobowca. Teraz jest gotów wymierzyć współczesnemu światu osobliwie pojmowaną sprawiedliwość.", "Jaume Collet-Serra", "Film akcji", 2022, NULL, 7, "https://i1.fdbimg.pl/x1/9q50wd42/400x580_rhyk7u.jpg");
INSERT INTO `dvds` VALUES (NULL, "Morderstwo po amerykańsku: Zwyczajna rodzina", "Film dokumentalny opowiadający przy użyciu niezmontowanych, autentycznych nagrań wideo o zaginięciu Shanann Watts i jej dzieci oraz o przerażającym dalszym ciągu sprawy.", "Jenny Popplewell", "Dokumnet", 2020, NULL, 7, "https://i1.fdbimg.pl/x1/ya4npi12/400x580_qgte31.jpg");
INSERT INTO `dvds` VALUES (NULL, "Joker", "Strudzony życiem komik popada w obłęd i staje się psychopatycznym mordercą.", "Todd Phillips", "Dramat", 2019, NULL, 4, "https://i1.fdbimg.pl/x1/j549v102/400x580_pxsj4e.jpg");
INSERT INTO `dvds` VALUES (NULL, "Nasze magiczne Encanto", "Dziewczynka pochodzi z kolumbijskiej rodziny, która obdarzona jest magicznymi mocami. Niestety ona sama nie posiada tego daru.", "Byron Howard", "Bajka", 2021, NULL, 6, "https://i1.fdbimg.pl/x1/novps532/400x580_r234zw.jpg");
INSERT INTO `dvds` VALUES (NULL, "Dwóch papieży", "Spotkanie w 2012 roku przyszłego papieża Franciszka z ówczesnym papieżem Benedyktem XVI jest okazją do rozmowy między dwoma głęboko wierzącymi osobami, o skrajnie różnym podejściu do wiary.", "Fernando Meirelles", "Komedia", 2019, NULL, 4, "https://i1.fdbimg.pl/x1/xaz0pzz1/400x580_q2grpo.jpg");
INSERT INTO `dvds` VALUES (NULL, "Bohater", "Fascynujący dramat o mężczyźnie, który odbywa karę więzienia za długi. Podczas dwudniowej przepustki w ręce Rahima trafia torba z kosztownościami – mężczyzna staje przed dylematem, czy przywłaszczyć zgubę, spłacić wierzyciela i zapewnić sobie wolność, czy też postąpić zgodnie ze swoim sumieniem i odnaleźć właściciela.", "Asghar Farhadi", "Dramat", 2021, NULL, 5, "https://i1.fdbimg.pl/x1/d9szxi42/400x580_rjs2sw.jpg");
INSERT INTO `dvds` VALUES (NULL, "Klondike", "Donbas, 2014 rok. Początek rosyjskiej inwazji na Ukrainę. Przerażający, przejmujący portret ludzkiej desperacji, a także wiary w siłę prawa i nadziei na lepsze jutro. Podążamy śladem pary spodziewającej się dziecka, której świat dosłownie zawalił się na głowę.", "Maryna Er Gorbach", "Dramat", 2022, NULL, 7, "https://i1.fdbimg.pl/x1/pujpy742/400x580_rftrx2.jpg");
INSERT INTO `dvds` VALUES (NULL, "Lombard", "Lombard jest poruszającą i nasyconą humorem opowieścią o ludziach, którzy walczą o przetrwanie i mało tego - pomagają jednocześnie tym, którzy bardziej tego potrzebują. Jola i Wiesiek stanowią parę zarówno w życiu, jak i w biznesie.", "Łukasza Kowalskiego", "Komedia", 2022, NULL, 3, "https://i1.fdbimg.pl/x1/vgqkzh42/400x580_rjfoqt.jpg");
INSERT INTO `dvds` VALUES (NULL, "Fatima", "Jest rok 1917. Świat pogrążony jest w mrokach pierwszej wojny światowej. Do małej portugalskiej wioski, Fatimy, podobnie jak do tysięcy miejscowości w całej Europie płyną dramatyczne wieści o tysiącach zabitych. Do domów wracają okaleczeni i pozbawieni nadziei weterani. W takich chwilach łatwo o zwątpienie i załamanie.", "Marco Pontecorvo", "Dramat", 2020, NULL, 7, "https://i1.fdbimg.pl/x1/zr2pxz22/400x580_qzz65c.jpg");
INSERT INTO `dvds` VALUES (NULL, "Paranormal Activity: Bliscy krewni", "Dokumentalistka Margot (Emily Bader) udaje się do odosobnionej społeczności Amiszów w nadziei na spotkanie i poznanie swojej dawno zaginionej matki oraz dalszej rodziny. Po serii dziwnych zdarzeń i odkryć zdaje sobie sprawę, że społeczność, która przyjęła ich do swojego domu, może ukrywać coś przerażającego…", "William Eubank", "Horror", 2021, NULL, 4, "https://i1.fdbimg.pl/x1/tgqs8432/400x580_r1j09j.jpg");
INSERT INTO `dvds` VALUES (NULL, "Bejbis", "Ada (Marta Żmuda Trzebiatowska) i Mikołaj (Grzegorz Małecki) od wielu lat tworzą udane małżeństwo będące rodzicami rezolutnej piętnastolatki (Barbara Papis). Poukładane życie pary wywróci do góry nogami pojawienie się nowego członka rodziny - Janka, uroczego dziecka, jednak nieplanowanego", "Andrzej Saramonowic", "Romantyczny", 2022, NULL, 5, "https://i1.fdbimg.pl/x1/p9010f42/400x580_ricyx8.jpg");